FROM jitesoft/tesseract-ocr

RUN pip3 install --upgrade pika redis requests flask pytesseract pillow pdf2image

WORKDIR  /srv 
COPY     worker-server.py /srv
ENV      FLASK_APP=worker-server.py
CMD      ["python3", "worker-server.py"]
