##
## You provide this
##

FROM python:3

RUN  pip3 install --upgrade pika redis jsonpickle requests flask google-cloud-storage

WORKDIR  /srv 
COPY     ["rest-server.py", "rest-client.py", "credentials.json", "/srv"]
ENV      FLASK_APP=rest-server.py GOOGLE_APPLICATION_CREDENTIALS=credentials.json
CMD      ["python", "rest-server.py"]