##
## You provide this
##

FROM python:3.9-alpine

RUN  pip3 install --upgrade pika redis jsonpickle requests flask

WORKDIR  /srv 
COPY     rest-server.py rest-client.py /srv
ENV      FLASK_APP=rest-server.py
CMD      ["python3", "rest-server.py"]